// 商品模拟数据
import { Product, ProductCategory, ProductSalesStats, InventoryAlert } from '../../types/product';

export const mockProductData: Product[] = [
  {
    id: 'prod_001',
    name: '静莱美焕颜精华液',
    category: '护肤品',
    description: '高效焕颜精华，深层滋养肌肤，改善细纹和暗沉',
    retailPrice: 298.00,
    agentPrice: 199.00,
    vipPrice: 179.00,
    partnerPrice: 159.00,
    costPrice: 120.00,
    stock: 156,
    soldCount: 842,
    unit: '瓶',
    specifications: ['30ml', '50ml', '100ml'],
    images: ['https://example.com/product1-1.jpg', 'https://example.com/product1-2.jpg'],
    tags: ['精华', '护肤', '焕颜', '热销'],
    status: 'active',
    commissionRate: 0.15,
    weight: 0.2,
    dimensions: { length: 5, width: 5, height: 15 },
    shippingType: 'free',
    shippingFee: 0,
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    isFeatured: true,
    isHot: true,
    salesTarget: 1000,
    createdAt: '2026-01-15T10:30:00Z',
    updatedAt: '2026-03-20T14:25:00Z'
  },
  {
    id: 'prod_002',
    name: '美肌洁面乳',
    category: '护肤品',
    description: '温和洁面，深层清洁不紧绷，适合所有肤质',
    retailPrice: 128.00,
    agentPrice: 88.00,
    vipPrice: 78.00,
    partnerPrice: 68.00,
    costPrice: 45.00,
    stock: 234,
    soldCount: 1567,
    unit: '支',
    specifications: ['120g', '200g'],
    images: ['https://example.com/product2-1.jpg'],
    tags: ['洁面', '护肤', '温和', '推荐'],
    status: 'active',
    commissionRate: 0.12,
    weight: 0.15,
    dimensions: { length: 4, width: 4, height: 12 },
    shippingType: 'flat_rate',
    shippingFee: 8,
    minOrderQuantity: 1,
    maxOrderQuantity: 200,
    isFeatured: true,
    isHot: true,
    salesTarget: 2000,
    createdAt: '2026-02-10T09:15:00Z',
    updatedAt: '2026-03-22T11:40:00Z'
  },
  {
    id: 'prod_003',
    name: '补水面膜',
    category: '面膜',
    description: '密集补水，改善干燥，使肌肤水润透亮',
    retailPrice: 168.00,
    agentPrice: 118.00,
    vipPrice: 108.00,
    partnerPrice: 98.00,
    costPrice: 60.00,
    stock: 89,
    soldCount: 2341,
    unit: '盒',
    specifications: ['5片装', '10片装'],
    images: ['https://example.com/product3-1.jpg', 'https://example.com/product3-2.jpg'],
    tags: ['面膜', '补水', '护肤', '热销'],
    status: 'active',
    commissionRate: 0.18,
    weight: 0.3,
    dimensions: { length: 15, width: 10, height: 2 },
    shippingType: 'free',
    shippingFee: 0,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    isFeatured: true,
    isHot: true,
    salesTarget: 3000,
    createdAt: '2025-12-05T14:20:00Z',
    updatedAt: '2026-03-24T16:55:00Z'
  },
  {
    id: 'prod_004',
    name: '抗皱眼霜',
    category: '护肤品',
    description: '淡化眼周细纹，改善黑眼圈，提拉紧致',
    retailPrice: 358.00,
    agentPrice: 258.00,
    vipPrice: 238.00,
    partnerPrice: 218.00,
    costPrice: 150.00,
    stock: 45,
    soldCount: 567,
    unit: '瓶',
    specifications: ['15ml'],
    images: ['https://example.com/product4-1.jpg'],
    tags: ['眼霜', '抗皱', '护肤'],
    status: 'active',
    commissionRate: 0.20,
    weight: 0.1,
    dimensions: { length: 3, width: 3, height: 8 },
    shippingType: 'flat_rate',
    shippingFee: 10,
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    isFeatured: false,
    isHot: false,
    salesTarget: 800,
    createdAt: '2026-02-28T16:45:00Z',
    updatedAt: '2026-03-25T09:30:00Z'
  },
  {
    id: 'prod_005',
    name: '防晒喷雾',
    category: '防晒',
    description: 'SPF50+高效防晒，清爽不粘腻，防水防汗',
    retailPrice: 198.00,
    agentPrice: 138.00,
    vipPrice: 128.00,
    partnerPrice: 118.00,
    costPrice: 75.00,
    stock: 167,
    soldCount: 892,
    unit: '瓶',
    specifications: ['100ml', '150ml'],
    images: ['https://example.com/product5-1.jpg'],
    tags: ['防晒', '夏季', '护肤'],
    status: 'active',
    commissionRate: 0.16,
    weight: 0.25,
    dimensions: { length: 6, width: 6, height: 18 },
    shippingType: 'calculated',
    shippingFee: 15,
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    isFeatured: true,
    isHot: true,
    salesTarget: 1200,
    createdAt: '2026-03-10T11:20:00Z',
    updatedAt: '2026-03-23T13:15:00Z'
  },
  {
    id: 'prod_006',
    name: '身体乳',
    category: '身体护理',
    description: '滋养保湿，改善干燥，持久留香',
    retailPrice: 158.00,
    agentPrice: 108.00,
    vipPrice: 98.00,
    partnerPrice: 88.00,
    costPrice: 55.00,
    stock: 12,
    soldCount: 456,
    unit: '瓶',
    specifications: ['250ml', '500ml'],
    images: ['https://example.com/product6-1.jpg'],
    tags: ['身体乳', '保湿', '护理'],
    status: 'out_of_stock',
    commissionRate: 0.14,
    weight: 0.35,
    dimensions: { length: 7, width: 7, height: 20 },
    shippingType: 'flat_rate',
    shippingFee: 12,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    isFeatured: false,
    isHot: false,
    salesTarget: 600,
    createdAt: '2026-01-20T13:40:00Z',
    updatedAt: '2026-03-24T18:20:00Z'
  },
  {
    id: 'prod_007',
    name: '男士洁面',
    category: '男士护肤',
    description: '男士专用，控油祛痘，清爽洁净',
    retailPrice: 138.00,
    agentPrice: 98.00,
    vipPrice: 88.00,
    partnerPrice: 78.00,
    costPrice: 50.00,
    stock: 78,
    soldCount: 321,
    unit: '支',
    specifications: ['150g'],
    images: ['https://example.com/product7-1.jpg'],
    tags: ['男士', '洁面', '控油'],
    status: 'active',
    commissionRate: 0.13,
    weight: 0.18,
    dimensions: { length: 5, width: 5, height: 14 },
    shippingType: 'free',
    shippingFee: 0,
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
    isFeatured: false,
    isHot: false,
    salesTarget: 500,
    createdAt: '2026-02-15T15:10:00Z',
    updatedAt: '2026-03-22T10:05:00Z'
  },
  {
    id: 'prod_008',
    name: '护手霜',
    category: '手部护理',
    description: '滋润保湿，修复干燥，四季适用',
    retailPrice: 88.00,
    agentPrice: 58.00,
    vipPrice: 48.00,
    partnerPrice: 38.00,
    costPrice: 25.00,
    stock: 256,
    soldCount: 1789,
    unit: '支',
    specifications: ['50g', '100g'],
    images: ['https://example.com/product8-1.jpg'],
    tags: ['护手霜', '保湿', '护理', '热销'],
    status: 'active',
    commissionRate: 0.10,
    weight: 0.08,
    dimensions: { length: 3, width: 3, height: 10 },
    shippingType: 'free',
    shippingFee: 0,
    minOrderQuantity: 1,
    maxOrderQuantity: 200,
    isFeatured: true,
    isHot: true,
    salesTarget: 2500,
    createdAt: '2025-11-25T09:50:00Z',
    updatedAt: '2026-03-21T14:35:00Z'
  },
  {
    id: 'prod_009',
    name: '卸妆水',
    category: '卸妆',
    description: '温和卸妆，清洁彻底，不刺激肌肤',
    retailPrice: 148.00,
    agentPrice: 108.00,
    vipPrice: 98.00,
    partnerPrice: 88.00,
    costPrice: 65.00,
    stock: 0,
    soldCount: 654,
    unit: '瓶',
    specifications: ['200ml', '400ml'],
    images: ['https://example.com/product9-1.jpg'],
    tags: ['卸妆', '清洁', '护肤'],
    status: 'out_of_stock',
    commissionRate: 0.17,
    weight: 0.28,
    dimensions: { length: 6, width: 6, height: 16 },
    shippingType: 'flat_rate',
    shippingFee: 8,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    isFeatured: false,
    isHot: false,
    salesTarget: 1000,
    createdAt: '2026-01-30T12:25:00Z',
    updatedAt: '2026-03-25T08:45:00Z'
  },
  {
    id: 'prod_010',
    name: '精华套装',
    category: '套装',
    description: '三重精华套装，日夜修复，全面护理',
    retailPrice: 658.00,
    agentPrice: 458.00,
    vipPrice: 428.00,
    partnerPrice: 398.00,
    costPrice: 280.00,
    stock: 34,
    soldCount: 189,
    unit: '套',
    specifications: ['日间精华30ml+夜间精华30ml+眼霜15ml'],
    images: ['https://example.com/product10-1.jpg', 'https://example.com/product10-2.jpg'],
    tags: ['套装', '精华', '护肤', '推荐'],
    status: 'active',
    commissionRate: 0.25,
    weight: 0.5,
    dimensions: { length: 20, width: 15, height: 8 },
    shippingType: 'calculated',
    shippingFee: 20,
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
    isFeatured: true,
    isHot: false,
    salesTarget: 300,
    createdAt: '2026-03-05T14:55:00Z',
    updatedAt: '2026-03-24T17:10:00Z'
  }
];

export const mockCategories: ProductCategory[] = [
  { id: 'cat_001', name: '护肤品', description: '面部护理产品', parentId: undefined, level: 1, icon: '💆‍♀️', sortOrder: 1, productCount: 4 },
  { id: 'cat_002', name: '面膜', description: '各种功效面膜', parentId: undefined, level: 1, icon: '🎭', sortOrder: 2, productCount: 1 },
  { id: 'cat_003', name: '防晒', description: '防晒产品', parentId: undefined, level: 1, icon: '☀️', sortOrder: 3, productCount: 1 },
  { id: 'cat_004', name: '身体护理', description: '身体护理产品', parentId: undefined, level: 1, icon: '🛁', sortOrder: 4, productCount: 1 },
  { id: 'cat_005', name: '男士护肤', description: '男士专用护肤品', parentId: undefined, level: 1, icon: '👨', sortOrder: 5, productCount: 1 },
  { id: 'cat_006', name: '手部护理', description: '手部护理产品', parentId: undefined, level: 1, icon: '🤲', sortOrder: 6, productCount: 1 },
  { id: 'cat_007', name: '卸妆', description: '卸妆产品', parentId: undefined, level: 1, icon: '🧴', sortOrder: 7, productCount: 1 },
  { id: 'cat_008', name: '套装', description: '产品组合套装', parentId: undefined, level: 1, icon: '🎁', sortOrder: 8, productCount: 1 },
  { id: 'cat_009', name: '洁面类', description: '洁面产品', parentId: 'cat_001', level: 2, icon: '🧼', sortOrder: 9, productCount: 2 },
  { id: 'cat_010', name: '精华类', description: '精华产品', parentId: 'cat_001', level: 2, icon: '💧', sortOrder: 10, productCount: 2 }
];

export const mockSalesStats: ProductSalesStats[] = [
  {
    productId: 'prod_001',
    productName: '静莱美焕颜精华液',
    dateRange: '本月',
    totalSales: 156,
    totalRevenue: 31044.00,
    totalOrders: 89,
    avgDailySales: 5.2,
    salesTrend: 'up',
    trendPercentage: 15.8
  },
  {
    productId: 'prod_002',
    productName: '美肌洁面乳',
    dateRange: '本月',
    totalSales: 234,
    totalRevenue: 20592.00,
    totalOrders: 156,
    avgDailySales: 7.8,
    salesTrend: 'up',
    trendPercentage: 22.5
  },
  {
    productId: 'prod_003',
    productName: '补水面膜',
    dateRange: '本月',
    totalSales: 289,
    totalRevenue: 33452.00,
    totalOrders: 167,
    avgDailySales: 9.6,
    salesTrend: 'up',
    trendPercentage: 31.2
  },
  {
    productId: 'prod_005',
    productName: '防晒喷雾',
    dateRange: '本月',
    totalSales: 142,
    totalRevenue: 19596.00,
    totalOrders: 98,
    avgDailySales: 4.7,
    salesTrend: 'up',
    trendPercentage: 45.3
  },
  {
    productId: 'prod_008',
    productName: '护手霜',
    dateRange: '本月',
    totalSales: 324,
    totalRevenue: 18792.00,
    totalOrders: 213,
    avgDailySales: 10.8,
    salesTrend: 'stable',
    trendPercentage: 2.3
  },
  {
    productId: 'prod_004',
    productName: '抗皱眼霜',
    dateRange: '本月',
    totalSales: 67,
    totalRevenue: 17286.00,
    totalOrders: 45,
    avgDailySales: 2.2,
    salesTrend: 'down',
    trendPercentage: -8.7
  },
  {
    productId: 'prod_010',
    productName: '精华套装',
    dateRange: '本月',
    totalSales: 23,
    totalRevenue: 10534.00,
    totalOrders: 18,
    avgDailySales: 0.8,
    salesTrend: 'up',
    trendPercentage: 12.4
  }
];

export const mockInventoryAlerts: InventoryAlert[] = [
  {
    id: 'alert_001',
    productId: 'prod_006',
    productName: '身体乳',
    currentStock: 12,
    threshold: 20,
    alertType: 'low_stock',
    status: 'active',
    createdAt: '2026-03-24T10:15:00Z'
  },
  {
    id: 'alert_002',
    productId: 'prod_009',
    productName: '卸妆水',
    currentStock: 0,
    threshold: 10,
    alertType: 'out_of_stock',
    status: 'active',
    createdAt: '2026-03-25T08:45:00Z'
  },
  {
    id: 'alert_003',
    productId: 'prod_004',
    productName: '抗皱眼霜',
    currentStock: 45,
    threshold: 50,
    alertType: 'low_stock',
    status: 'active',
    createdAt: '2026-03-23T14:30:00Z'
  },
  {
    id: 'alert_004',
    productId: 'prod_007',
    productName: '男士洁面',
    currentStock: 78,
    threshold: 100,
    alertType: 'low_stock',
    status: 'resolved',
    createdAt: '2026-03-20T09:20:00Z',
    resolvedAt: '2026-03-22T10:05:00Z'
  }
];